---
driver:
  name: dokken
  chef_version: 12.7.2
  privileged: true
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  name: inspec
platforms:
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
  run_list:
  - recipe[apt]
  - recipe[sudo-user]
  attributes:
    cdo-cloudwatch-logger:
      dry_run: true
      syslog_size: 256
suites:
- name: default
  run_list:
  - recipe[cdo-cloudwatch-logger]
